spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-poll?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
